name: test job
on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Updated version'
          required: true
          default: 'v'
          type: string
jobs:
  test:
     runs-on: [ ubuntu-latest]
     steps:
      - name: test1
        run: |
         echo ${{ github.run_number }}
         var="v${{ inputs.version }}"
         var1="${var1:1}"  
         new=$((28-1))
         echo $new
         blue=$(($var1-1))
         echo "hhh-$blue"
