name: test job
on:
  push:
    branches: [ main ]
jobs:
  test:
     runs-on: [ ubuntu-latest]
     steps:
      - name: test1
        run: |
         echo ${{ github.run_number }}
         new=$((28-1))
         echo $new
         blue=$((${{github.run_number }}-1))
         echo "hhh-$blue"
